apiVersion: v1
kind: BuildConfig
metadata:
  name: atpco-rhel-utils
  labels:
    build: atpco-rhel-utils
spec:
  source:
    type: Git
    git:
      uri: 'https://atphg.atpco.org/gitrepos/BaseImages.git'
    contextDir: atp-rhel-utils
    secrets: []
    sourceSecret:
      name: scmsecret    
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'rhel7.2:latest'
  output:
    to:
      kind: DockerImage
      name: 'artmgt01.atpco.org:9091/atpco-rhel-utils:1.0'
  resources: {  }
  postCommit: {  }
